name: ROS Noetic Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t yourdockerhubusername/ros-noetic-pt-controller-test .

    - name: Run tests
      run: |
        docker run --rm yourdockerhubusername/ros-noetic-pt-controller-test /bin/bash -c "source /opt/ros/noetic/setup.bash && cd /catkin_ws && catkin test"
